SystemSchool/Models/Alumno.cs
namespace SystemSchool.Models
{
    public class Alumno
    {
        public int Matricula_Alumno { get; set; }

        public string Nombre_Alumno { get; set; }

        public int Edad_Alumno { get; set; }

        public string Semestre_Alumno { get; set; }

        public string  Genero_Alumno { get; set; }

    }
}

SystemSchool/Models/ErrorViewModel.cs
namespace SystemSchool.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SystemSchool/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;
using SystemSchool.Data;
using SystemSchool.Models;

namespace SystemSchool.Controllers
{
    public class AlumnoController : Controller
    {
        readonly SchoolDAL Context = new SchoolDAL();
        public IActionResult Index(string texto)
        {
            if(texto != null )
            {
                IEnumerable<Alumno> ListadoAlumno = Context.Buscador(texto);
                return View(ListadoAlumno);
            }
            
                IEnumerable<Alumno> ListadoAlumnos = Context.MostrarAlumnos();
                return View(ListadoAlumnos);
          
           
        }

        //GET
        public IActionResult CrearAlumno()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CrearAlumno(Alumno Alumno)
        {
            if (ModelState.IsValid)
            {
                Context.CrearAlumno(Alumno);
                return RedirectToAction("Index");
            }
            return View(Alumno);
        }

        //GET
        public IActionResult EditarAlumno(int Matricula_Alumno)
        {
            if(Matricula_Alumno == null) { return NotFound(); }
            Alumno Alumno = Context.MostraralumnoPorId(Matricula_Alumno);
            if(Alumno == null) { return NotFound(); }
            return View(Alumno);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditarAlumno(int Matricula_Alumno, Alumno Alumno)
        {
            

            if (ModelState.IsValid)
            {
                Context.EditarAlumno(Alumno);
                return RedirectToAction("Index");
            }

            return View(Alumno);
        }
    }
}

SystemSchool/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using SystemSchool.Models;

namespace SystemSchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SystemSchool/Views/Alumno/CrearAlumno.cshtml
@model SystemSchool.Models.Alumno

@{
    ViewData["Title"] = "Crear Alumno";
}

<h1>Crear Alumno</h1>

<h4>Alumno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CrearAlumno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre_Alumno" class="control-label"></label>
                <input asp-for="Nombre_Alumno" class="form-control" />
                <span asp-validation-for="Nombre_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad_Alumno" class="control-label"></label>
                <input asp-for="Edad_Alumno" class="form-control" />
                <span asp-validation-for="Edad_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semestre_Alumno" class="control-label"></label>
                <input asp-for="Semestre_Alumno" class="form-control" />
                <span asp-validation-for="Semestre_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero_Alumno" class="control-label"></label>
                <input asp-for="Genero_Alumno" class="form-control" />
                <span asp-validation-for="Genero_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary my-1" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary" asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SystemSchool/Views/Alumno/EditarAlumno.cshtml
@model SystemSchool.Models.Alumno

@{
    ViewData["Title"] = "EditarAlumno";
}

<h1>EditarAlumno</h1>

<h4>Alumno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarAlumno">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group ">
                <label asp-for="Matricula_Alumno" class="control-label"></label>
                <input asp-for="Matricula_Alumno" class="form-control disabled" />
                <span asp-validation-for="Matricula_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre_Alumno" class="control-label"></label>
                <input asp-for="Nombre_Alumno" class="form-control" />
                <span asp-validation-for="Nombre_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad_Alumno" class="control-label"></label>
                <input asp-for="Edad_Alumno" class="form-control" />
                <span asp-validation-for="Edad_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Semestre_Alumno" class="control-label"></label>
                <input asp-for="Semestre_Alumno" class="form-control" />
                <span asp-validation-for="Semestre_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero_Alumno" class="control-label"></label>
                <input asp-for="Genero_Alumno" class="form-control" />
                <span asp-validation-for="Genero_Alumno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SystemSchool/Views/Alumno/Index.cshtml
@model IEnumerable<SystemSchool.Models.Alumno>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a class = "btn btn-secondary" asp-action="CrearAlumno">Create New</a>
</p>
<form asp-controller="Alumno" asp-action="Index">
    <input type="text" name="texto"/>
    <input type="submit" class="btn btn-primary" value="Buscar"/>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Matricula_Alumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Alumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad_Alumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Semestre_Alumno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero_Alumno)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula_Alumno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_Alumno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad_Alumno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Semestre_Alumno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero_Alumno)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditarAlumno", new {  Matricula_Alumno=item.Matricula_Alumno }, new{@class = "btn btn-warning"}) |
               
            </td>
        </tr>
}
    </tbody>
</table>

SystemSchool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SystemSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SystemSchool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SystemSchool.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SystemSchool</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumno" asp-action="Index">Alumnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SystemSchool - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>